### ISSUE TITLE
Scrolling is laggy in reader.

### ISSUE THREAD

**Issue by Sadwhy** [dstark5/Openlib#11]
Self explanatory. 
I'm on a Samsung a23, android 13. The app version is 1.0.0

**Comment by dstark5** [comment]
This is bug is associated with the epub_viewer package.I will update once the package got a improved version

**Comment by dstark5** [comment]
Yes, But the package used now has a good maintenance and updated frequently other packages doesn't have active maintenance.That's why we stuck to the package

**Comment by Sadwhy** [comment]
Is that so.

**Comment by dstark5** [comment]
Yes,soon read in other app feature also be added

**Comment by dstark5** [comment]
Hi, The issue have been fixed in the latest release 1.0.1 update it and if you satisfied close the issue
