### ISSUE TITLE
Stuck on Solve Captcha Screen

### ISSUE THREAD

**Issue by DhagonHunt** [dstark5/Openlib#116]
After I solve the captcha, the screen goes directly to the download link on the website instead of starting the download. This happens every time I try to add a book to the library. I use an S22, Android 14.

**Comment by MrLoo1** [comment]
this bug, not fix 

https://github.com/user-attachments/assets/981da769-180c-4a25-b8bc-fb2326698507

**Comment by dstark5** [comment]
Hi,
This issue have been fixed in the latest version of app

Thank you

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
