### ISSUE TITLE
Trending Feature Request Connection Error

### ISSUE THREAD

**Issue by sainvignesh** [dstark5/Openlib#120]
![Screenshot_20241013_072427.jpg](https://github.com/user-attachments/assets/d1a3f723-fef0-4d26-af5e-af8684f87174)

**Comment by Salamanderxcross** [comment]
The same, please fixe the problem

**Comment by Prithhi** [comment]
Same issue please fix it

**Comment by dstark5** [comment]
@sainvignesh @Salamanderxcross @Prithhi 

Hi,
Thanks for reporting will fix and release a new version  ASAP
