### ISSUE TITLE
After searching a grey screen is coming 

### ISSUE THREAD

**Issue by Prithhi** [dstark5/Openlib#127]
After searching a grey screen is coming

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by monoira** [comment]
same thing happens to me too

**Comment by 44cK3r** [comment]
Same here I really wanted to get some more joke books

**Comment by Prithhi** [comment]
Closed. Yet not resolved

**Comment by dstark5** [comment]
Hi Everyone 👋 
Will fix this issue ASAP

**Comment by anshull-saxena** [comment]
@Prithhi, could you please send me a screenshot or something similar? I'll do my best to fix it.

**Comment by 44cK3r** [comment]
> @Prithhi @monoira , could you please send me a screenshot or something similar? I'll do my best to fix it.

I know you didn't ask me but this is what is happening
(after hitting search I had to be so quick to get the second screenshot before it went grey)

![Screenshot_2024-11-01-19-24-02-61_2ff6865c0065dc15717bfe2a6737744c.jpg](https://github.com/user-attachments/assets/0e7005c5-e787-43f7-8f8f-78f297bc320f)

![Screenshot_2024-11-01-19-24-18-65_2ff6865c0065dc15717bfe2a6737744c.jpg](https://github.com/user-attachments/assets/dd7a001b-7a14-4197-bc21-cfe6b91a9f56)

![Screenshot_2024-11-01-19-24-21-32_2ff6865c0065dc15717bfe2a6737744c.jpg](https://github.com/user-attachments/assets/58eb7195-779e-47b3-a9fa-a444f517a529)
