### ISSUE TITLE
[Feature Request] Support to save files in /sdcard/ directory.

### ISSUE THREAD

**Issue by confident-hate** [dstark5/Openlib#14]
Hi, 
I request you to add storage support for the app. Right now I am not able to move files out of /data/data/com.* folder.

Or can you please provide debuggable releases, so that we can get files via "run-as" as I already have access to adb shell via rish in termux with [Shizuku](https://github.com/RikkaApps/Shizuku) 

```
adb shell
run-as com.your.packagename 
cp /data/data/com.your.packagename/
```

Thanks

**Comment by dstark5** [comment]
Sure, In upcoming release the app will use internal storage to store file

**Comment by confident-hate** [comment]
> Sure, In upcoming release the app will use internal storage to store file

You can mark it as solved, now I can copy files out of app directory via "open with" fature.
