### ISSUE TITLE
the chapter picker from the side does not work properly, or does not work at all.

### ISSUE THREAD

**Issue by github-user93** [dstark5/Openlib#16]
i have recorded a screen recording that shows the issue.
https://youtu.be/BwHCbH5nY6k

**Comment by dstark5** [comment]
The error is caused by epub view package. I have got a lot of issue on GitHub regarding the Epub viewer package will change the reader to a better one in the next update

**Comment by dstark5** [comment]
Hi, The issue have been fixed in the latest release 1.0.1 update it and if you satisfied close the issue

**Comment by dstark5** [comment]
The new version 1.0.3 fixed the issues use it with a VPN
