### ISSUE TITLE
Back button needed

### ISSUE THREAD

**Issue by syswraith** [dstark5/Openlib#17]
Add a back button on the top left, near the Openlib logo. It just feels natural.
![Screenshot_20230824-190133~3](https://github.com/dstark5/Openlib/assets/77088155/373ff156-311c-4cdb-b548-74340d8ee0ad)

**Comment by dstark5** [comment]
Sure, will add in the upcoming update

**Comment by vijaymehrotra** [comment]
Can I work on this issue... I know how to add a back button.

**Comment by dstark5** [comment]
Yeah sure

**Comment by vijaymehrotra** [comment]
i was trying to run this code on my system but an error occurs : 

lib/ui/epub_viewer.dart:131:39: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:universal_file/src/io/file.dart' ('/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/pub.dev/universal_file-1.0.0/lib/src/io/file.dart').    
      document: EpubDocument.openFile(File(widget.filePath)),

// what should i do

**Comment by dstark5** [comment]
Sorry for the delayed response

May I know what changes did have made in the lib

**Comment by vijaymehrotra** [comment]
I didn't change anything. 
I just forked the repository and tried to run it, and it is showing this error. 

**Error: The argument type 'File/1/' can't be assigned to the parameter type 'File/2/'.**

**Comment by dstark5** [comment]
would you provide a more detailed error log for this

**Comment by vijaymehrotra** [comment]
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/ui/epub_viewer.dart:131:39: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:universal_file/src/io/file.dart' ('/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/pub.dev/universal_file-1.0.0/lib/src/io/file.dart').
      document: EpubDocument.openFile(File(widget.filePath)),


This is the error showing in my terminal

**Comment by dstark5** [comment]
This project is designed to work on android kindly use an android emulator or device to run the project

**Comment by syswraith** [comment]
Closing this issue since my feature request has been fulfilled.
