### ISSUE TITLE
FEEDBACK: Bottom Navigation Bar background color should be white in light mode 

### ISSUE THREAD

**Issue by basitali1509** [dstark5/Openlib#25]
### **Description**

For a better UI, or you can say more pleasing, the background color of the Bottom Navigation Bar should be white in light mode; in that case, the icon color of non-active tabs would be black.

### **Before**

<img width="248" alt="OpenLib-darkcolor" src="https://github.com/dstark5/Openlib/assets/84122396/d9d21c1e-e2b1-4988-94ca-690bc49532a5">

### **After**

<img width="283" alt="OpenLib-lightmode" src="https://github.com/dstark5/Openlib/assets/84122396/f59368c6-fc0e-449b-a349-a09de20346d1">

**Comment by dstark5** [comment]
Yeah, that looks nice will sure change it in the upcoming update 
What about light grey will it be a better a choice for light theme

**Comment by basitali1509** [comment]
I tried grey with shade 300, and it looks good, but in my opinion, white in light mode and black in dark mode look like a perfect combination.

**Comment by dstark5** [comment]
released a new update to fix 'download failed' error 
The change you mentioned will be added in the upcoming version
