### ISSUE TITLE
File Type on the Search Page

### ISSUE THREAD

**Issue by tunamert0** [dstark5/Openlib#31]
I think it is necessary to be able to see the file types of the books directly on the search page before entering the book page.

**Comment by dstark5** [comment]
Will sure add it in the upcoming update 👍

**Comment by bikraj2** [comment]
can you assign me this issue?

**Comment by dstark5** [comment]
> can you assign me this issue?

Hi, Thanks for showing your interest ☺️
But the feature is added and will be pushed to GitHub tomorrow.

You can take a look at other issues and can work on it.

Thank you

**Comment by dstark5** [comment]
The new version 1.0.3 fixed the issues use it with a VPN
