### ISSUE TITLE
Showing error on opening book

### ISSUE THREAD

**Issue by Xtreme-Tech** [dstark5/Openlib#33]
Stack Trace
#0
(package:dio/src/dio_mixin.dart:507) #1
#2
future_impl.dart:174) #3
(dart:async/future_impl.dart:852) #4
future_impl.dart:873) #5
future_impl.dart:649) #6
future_impl.dart:60)
#7
future_impl.dart:26) #8
#9
#10
future_impl.dart:171) #11
(dart:async/future_impl.dart:852) #12
future_impl.dart:873) #13
future_impl.dart:649) #14
closure> (dart:async/future_impl.dart:550) #15
schedule_microtask.dart:40) #16
schedulemicrotask.dart:49)

**Comment by dstark5** [comment]
did you get the error message
"The request returned an invalid status code 522"

**Comment by Xtreme-Tech** [comment]
Yes I got this error on opening any book how can I fix it

**Comment by dstark5** [comment]
The new version 1.0.3 fixed the issues use it with a VPN
