### ISSUE TITLE
When I try to open a pdf I always encounter this error.

### ISSUE THREAD

**Issue by yhrjfj** [dstark5/Openlib#34]
![Screenshot_20231016_215153.jpg](https://github.com/dstark5/Openlib/assets/102893295/701f483c-17a1-4ba9-8694-79deb6cdad5d)

**Comment by dstark5** [comment]
The domain annas-achive.gs is down and throwing timeout error
Will sure fix the app within couple of days
Will provide a new update

**Comment by dstark5** [comment]
The new version 1.0.3 fixed the issues use it with a VPN
