### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [dstark5/Openlib#36]
Looks like you forgot to increase `versionCode` with each release. As this is what Android uses to tell versions apart, nobody received any update notification (so some might still sit on an old release, unaware of any updates being available). It is [currently](https://github.com/dstark5/Openlib/blob/main/pubspec.yaml#L19) still set to `1` (the part following the `+`). Can you please take care to increase it with each future release? Thanks in advance!

**Comment by dstark5** [comment]
Thank you bro😊
Will sure update the version on updates👍

**Comment by IzzySoft** [comment]
Completed where?

```
version: 1.0.3+1
```

it is still `+1` where it instead should at least be `+4` now (there are 4 releases already).

**Comment by IzzySoft** [comment]
`versionCode` is what Android uses internally to tell versions apart. So `<applicationId>_<versionName>` is a unique identifier for a specific version of an app. As `applicationId` identifies the app and thus cannot be changed, not changing `versionName` means a new release *overwrites* the previous one in the repo – and nobody who's installed the app will ever receive any update notification (as to Android, nothing changed: the unique identifier is still the same).

So yes, you should increase the **integer** following the `+` with each release you make.

**Comment by dstark5** [comment]
Okay bro I will update versioncode
Should I update now or in the next release

**Comment by IzzySoft** [comment]
Maybe update it in your `pubspec.yaml` now so you cannot forget it – and have it take effect with the next release then, as the current release was already pulled? I'll leave that decision to you. As long as it's fixed with the next release :wink:
