### ISSUE TITLE
No result Found Problem.

### ISSUE THREAD

**Issue by Gurupatel007** [dstark5/Openlib#37]
After two days of downloading app whenever I try to open any book to download it says no results found for each and every book.

**Comment by dstark5** [comment]
Will fix it and provide update tommorow

**Comment by balogun14** [comment]
@dstark5 @Gurupatel007 can you explain this issue more i will like to work on this

**Comment by dstark5** [comment]
Hi 
The issue you faced is related to url formatting of Anna's Archive changed that's why there is no results found

**Comment by dstark5** [comment]
> @dstark5 @Gurupatel007 can you explain this issue more i will like to work on this

Yes your contribution is always welcomed
But there is a major update with cloudflare clearance for openlib and you can contribute after that😊

**Comment by lurkingalt** [comment]
Is there any update on this?

**Comment by dstark5** [comment]
Yes the update will be provided today

**Comment by powerfulparadox** [comment]
I'm now getting results, but tapping a result sends me to a cloudflare captcha which drops me back at the results page. So I'm stuck in a loop with no access to the download page.

**Comment by dstark5** [comment]
the new version require a VPN to function properly without VPN the app will produce result you mentioned

**Comment by dstark5** [comment]
Try using a VPN
