### ISSUE TITLE
can't download files

### ISSUE THREAD

**Issue by semokkuklek** [dstark5/Openlib#40]
hello, there is a problem with downloading files, even with VPN there is an error "download failed, try again."
some files are starts downloading but eventually get stuck in a middle
![Screenshot_20231117_230309](https://github.com/dstark5/Openlib/assets/151207952/54e61deb-712d-47d0-b8f6-b4d8b10556ba)

**Comment by dstark5** [comment]
will be fixed with in a couple of days

**Comment by dstark5** [comment]
The bug is fixed in new version 1.0.3 beta.1 ,kindly update
