### ISSUE TITLE
Solve Captcha

### ISSUE THREAD

**Issue by ahmedalbanna** [dstark5/Openlib#41]
When I open any book from the list, it asks me for a captcha, then I solve it by clicking on the correct box, then it loads and repeats again, and thus the information does not open the book, and the captcha solution remains the only one to read the book.

I/chromium( 6105): [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.", source:  (0)
I/chromium( 6105): [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'hid'.", source:  (0)
I/chromium( 6105): [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)
I/chromium( 6105): [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'payment'.", source:  (0)
I/chromium( 6105): [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'serial'.", source:  (0)
I/chromium( 6105): [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'usb'.", source:  (0)
![Screenshot_20231118-053403](https://github.com/dstark5/Openlib/assets/37414936/d4fca017-fc28-48b5-a240-03d85501dce8)
![Screenshot_20231118-053411](https://github.com/dstark5/Openlib/assets/37414936/6a6878f1-f321-4b2c-9737-395f24eff8a9)

**Comment by dstark5** [comment]
Using a VPN will fix this issue otherwise the app loops between captcha screen and captcha required screen
