### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by inson1** [dstark5/Openlib#42]
https://www.reddit.com/r/Annas_Archive/comments/15o84ws/comment/jvsizxn/?utm_source=share&utm_medium=web2x&context=3

You said you are workin on it :)

How it is going?

**Comment by inson1** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13584

**Comment by inson1** [comment]
I think it is on f-droid to solve their issue with flutter. Or on Flutter to clean it up. Idk how could I help. 


Why dont you want Reproducible Builds? Idk how hard it would be.
And why target and compiled version isnt higher?

**Comment by dstark5** [comment]
Yes the fdroid need to solve it
Is reproducible build that hard?
Target version will be increased in next build
Thank you 😊

**Comment by inson1** [comment]
@dstark5 I think it shouldnt be that hard but I dont have any experience with that yet

**Comment by inson1** [comment]
@dstark5 great news! What about izzydroid now? I think we should keep it, but some apps leave after joining F-droid
I'm going to close this issue.

**Comment by dstark5** [comment]
> @dstark5 great news! and great work! What about izzydroid now? I think we should keep it, but some apps leave after joining F-droid I'm going to close this issue.

Yes, we can keep it
