### ISSUE TITLE
[BUG] "no results found" again

### ISSUE THREAD

**Issue by inson1** [dstark5/Openlib#52]
yes I'm using newest version v1.0.3-beta.2

#49 

PS change app version every time please :)

**Comment by dstark5** [comment]
Will fix this issue ASAP
Now a days Anna's Archive website changes a lot

**Comment by inson1** [comment]
@dstark5 
thank you for your hard work :)

I think its better, so people (and I) would know if they have the new version or not :)

**Comment by dstark5** [comment]
Done 
Bro, the app currently uses VPN to function properly I`ve tried to fix this issue but still doesn't could you help me in this

**Comment by dstark5** [comment]
> Done Bro, the app currently uses VPN to function properly I`ve tried to fix this issue but still doesn't could you help me in this

Here you can find me on discord 

https://discord.com/invite/rVA8gm9B

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
