### ISSUE TITLE
Reduce Captcha

### ISSUE THREAD

**Issue by suhan-paradkar** [dstark5/Openlib#59]
It would be better if the User could login(This may require webview with cookie capture, IIRC)

This would help with reducing pesky captcha screens (I assume the site uses cookies to authenticate).

Allowing user to set a random or custom user-agent string also might do the trick

**Comment by dstark5** [comment]
Hi,
the site uses browser check and the cookie is valid only for 10 to 20 min approximately,
Do you have any solutions ? feel free to tell  your, we can implement it.
