### ISSUE TITLE
Failed to download any book

### ISSUE THREAD

**Issue by 0xDkXy** [dstark5/Openlib#65]
No matter what book I tried, it was always "Download failed"

BTW, I used the proxy cuz I am in China.
![Screenshot_20240211-225014_Openlib](https://github.com/dstark5/Openlib/assets/55947248/1574d0aa-8aa6-4e43-8e00-cc3b7124a82b)

How can I fix it?

**Comment by FOSSAftethought** [comment]
Dealing with the same issue, for all desired books.

![Proof A](https://github.com/dstark5/Openlib/assets/159775343/d7dbf399-93b3-4801-adb3-38066a0e8ef8)
![proof D](https://github.com/dstark5/Openlib/assets/159775343/504c7e05-76ea-484e-9940-bfc5d25599f9)
![Proof C](https://github.com/dstark5/Openlib/assets/159775343/40acd9a2-de61-4fe4-a145-0d2d45dacfe1)
![Proof B](https://github.com/dstark5/Openlib/assets/159775343/c5bedbf5-f740-48c0-b20f-4bbeb6800c7e)

**Comment by alirizakeles** [comment]
Hi,

I have been experiencing the same issue. No need to share more screenshots. The ones above show exactly what pops up on my screen. I cannot see any error messages or anything giving clues about the problem. Is there anything I can do to debug?

Thanks,

-
Ali

**Comment by dstark5** [comment]
Hello guys 👋,

The issue is caused because of change in Anna's Archive website. Will fix the issue and release an update ASAP.

Thank you

**Comment by Cluck-Nugget** [comment]
@dstark5 looks like you added a commit to fix it, if it's working would you mind compiling a new release build?

**Comment by dstark5** [comment]
This error has been fixed in the latest version of app

**Comment by 0xDkXy** [comment]
> This error has been fixed in the latest version of app

Thanks, it works well.
