### ISSUE TITLE
Epub files are not opening in internal player working fine when i open in external player.

### ISSUE THREAD

**Issue by abhay7430** [dstark5/Openlib#75]
![VideoCapture_20240304-063711.jpg](https://github.com/dstark5/Openlib/assets/123221572/67f933a8-e4e4-4c3c-880a-f3646647fe81)

![VideoCapture_20240304-063702.jpg](https://github.com/dstark5/Openlib/assets/123221572/32bf7e90-c159-4b20-b1d9-df7d9e9cbfb0)

If you try to open one more time application got crashes, it was trying to open "Folio reader" in 0.1sec and it crashed.

**Comment by inson1** [comment]
@abhay7430 duplicate of #50, its known bug

**Comment by abhay7430** [comment]
> @abhay7430 duplicate of #50, its known bug, in meantime just use external epub reader

okay.

**Comment by inson1** [comment]
@abhay7430 may you also close it as its duplicate :) thank you

**Comment by abhay7430** [comment]
> @abhay7430 may you also close it as its duplicate :) thank you

then, I'm closing the topic.
