### ISSUE TITLE
Copy/Share URL

### ISSUE THREAD

**Issue by shuvashish76** [dstark5/Openlib#79]
Feature request for an option to copy/share the Anna's Archive URL.
Useful to save them e.g. on Calibre so that later on you can download whenever you want. Or save the URL for downloaded books so that in case you lose your files at least you've the catalog in CSV format & many similar use cases.

**Comment by shuvashish76** [comment]
Since they use MD5s hash in their link also to identify files
1. Option to copy MD5 (usecase: for comparision) (with copy icon)
2. Add an option to share the book link (usecase: share to a friend) (with share icon)

![2024-03-13_23-45](https://github.com/dstark5/Openlib/assets/48226312/caf17223-2a94-40b4-9afb-5a8273a0db72)

**Comment by dstark5** [comment]
Yeah sure will add it in the next update

**Comment by anshull-saxena** [comment]
Hi @dstark5 ,

I've implemented the requested feature in #126 ! Now, both the book title and thumbnail link are being shared successfully. The share message looks professional, and the image download functionality is working smoothly. Let me know if you'd like any further tweaks.

Looking forward to your feedback!
