### ISSUE TITLE
Trying to use this app and this came

### ISSUE THREAD

**Issue by eelalzep** [dstark5/Openlib#81]
![Screenshot_2024-03-29-22-18-40-623_com.app.openlib.jpg](https://github.com/dstark5/Openlib/assets/77693896/e87fba41-79e6-432e-aa99-020001ce069b)

![Screenshot_2024-03-29-22-18-35-617_com.app.openlib.jpg](https://github.com/dstark5/Openlib/assets/77693896/605fb2fb-49eb-437c-aedf-a6fbd0200aa7)

**Comment by dstark5** [comment]
Have you tried using a VPN?

**Comment by dstark5** [comment]
Hi @eelalzep,
try the latest 1.0.7 version this issue will be fixed.
