### ISSUE TITLE
[Bug] The app goes back To the search list after resolving Captcha

### ISSUE THREAD

**Issue by jerohnimaux** [dstark5/Openlib#88]
[Bug] The app goes back To the search list after resolving Captcha

**What I do**
1. I search for a book in the search bar
OR
I click on a book in the Trend list

A list of results is displayed

2. I click on the book I want to download

The captcha is loaded, I click on the captcha box. Captcha seems to be resolved

The app goes back to the result list 

**What it should do**
The app should display the book information and the dowload links for this book

**My system**
Openlib 1.0.6
GrapheneOS with Android 14

**Comment by collitamd** [comment]
Me pasa lo mismo hace 2 días...uso vpn y lo mismo

**Comment by lichingyun** [comment]
this happen also to me, I am using the latest version from github on Oneplus Nord 2 android 13 (original rom not modded)

**Comment by mricci82** [comment]
Hi, I encounter the same issue on a Samsung Galaxy A53 running Android 13.
This is a blocker.

**Comment by dstark5** [comment]
Hi 👋 ,
This is caused due to a change in Anna's archive website they made a 120 seconds wait time to get the download link will try to fix it ASAP.

**Comment by lichingyun** [comment]
today the app is working well @dstark5 , maybe there is some change on the website

**Comment by dstark5** [comment]
Hi @jerohnimaux ,
This issue is fixed in the latest 1.0.7 version.
Thank you
