### ISSUE TITLE
No mirrors available!

### ISSUE THREAD

**Issue by SAMluci666** [dstark5/Openlib#95]
Clicking on add to my library button for any and all books gives me the "No mirrors available error! What should I do?

**Comment by Ankurrawat-12** [comment]
is the error resolved?

**Comment by SAMluci666** [comment]
No, still facing the same issue.

**Comment by Morphanz** [comment]
I'm also having the same issues for almost 2 days now 😭

**Comment by TvT82** [comment]
Same here too

**Comment by tru1mac** [comment]
same

**Comment by MadH34ven** [comment]
Just downloaded and same. Bummer :(

**Comment by elfefe** [comment]
Same here ! Tried "rich larson" and "la malerune", none of the five first links work.

**Comment by holmesworcester** [comment]
Same issue.

**Comment by PrathamNabira** [comment]
It was my first time using this app I was super excited, it's a shame i am having the same issue

**Comment by Bataki16** [comment]
Same issue.

**Comment by clovis-dugue** [comment]
@dstark5 should you want to merge this, you may want to check out my fork, I've updated a few things to be compatible with the latest Flutter version

Note I've never developed in Flutter before so everything may not be up to standards, but feel free to cherry-pick whatever

**Comment by Chinguuuu** [comment]
How do I download the fixed version?

**Comment by holmesworcester** [comment]
I have the same question! When will the fix be live in f-droid?

**Comment by desmondalohan** [comment]
Still broken, every book I try to download says that there are no mirrors available.
