### ISSUE TITLE
No available mirrors


### ISSUE THREAD

**Issue by droidjedininja** [dstark5/Openlib#97]
I can't download a single book. I've been using this app since I discovered it and would hate to uninstall it. It's a great resource for people who love to read and can't afford to purchase books. I love this app. Pls Fix

**Comment by SomeDudeBrosky** [comment]
I have the she issue

**Comment by clovis-dugue** [comment]
Duplicate https://github.com/dstark5/Openlib/issues/95

**Comment by dstark5** [comment]
Hi,
This issue is fixed in latest version 1.0.7
