### ISSUE TITLE
No mirrors available

### ISSUE THREAD

**Issue by SomeDudeBrosky** [dstark5/Openlib#99]
This is on all devices

**Comment by clovis-dugue** [comment]
Duplicate https://github.com/dstark5/Openlib/issues/95

**Comment by dstark5** [comment]
Hi 👋 
This issue will be fixed in one or two days

**Comment by SomeDudeBrosky** [comment]
> Hi 👋 
> This issue will be fixed in one or two days 

Yayyyyy!!!!! Thank you so much!! 💛😁🎉🎊✨📖📕

**Comment by dstark5** [comment]
Hi EveryOne,
This issue is fixed in the latest version 1.0.7 , Thanks @clovis-dugue for the support.
